"""
config.py — Load hyperparameters from config.toml and expose them as typed
module-level constants.

All other scripts import their tunable values from here rather than defining
them inline, so every parameter has a single source of truth in config.toml.

First guesses (computed offline by compute_first_guess.py) are stored
separately in first_guesses.json and accessed via get_first_guess().
"""

import json
from pathlib import Path

try:
    import tomllib          # built-in since Python 3.11
except ImportError:
    try:
        import tomli as tomllib   # pip install tomli  (Python 3.9 / 3.10)
    except ImportError:
        raise ImportError(
            "Python 3.11+ is required, or install 'tomli': pip install tomli"
        )

_CONFIG_PATH = Path(__file__).parent / "config.toml"

with _CONFIG_PATH.open("rb") as _f:
    _cfg = tomllib.load(_f)

# ── [api] ────────────────────────────────────────────────────────────────────
BASE_URL:       str   = _cfg["api"]["base_url"]
VERIFY_SSL:     bool  = _cfg["api"]["verify_ssl"]
MAX_RETRIES:    int   = _cfg["api"]["max_retries"]
RETRY_BACKOFF:  float = _cfg["api"]["retry_backoff"]

# ── [game] ───────────────────────────────────────────────────────────────────
MAX_ATTEMPTS:   int   = _cfg["game"]["max_attempts"]

# ── [solver] ─────────────────────────────────────────────────────────────────
EVAL_LIMIT:          int = _cfg["solver"]["eval_limit"]
HEURISTIC_PRESAMPLE: int = _cfg["solver"].get("heuristic_presample", 0)

# ── [benchmark] ──────────────────────────────────────────────────────────────
SOLVERS: list[str] = _cfg["benchmark"]["solvers"]


_FIRST_GUESSES_PATH = Path(__file__).parent / "first_guesses.json"


def get_first_guess(size: int, solver_name: str) -> str | None:
    """Return the pre-computed first guess for a (size, solver) combination.

    Reads from first_guesses.json (generated by compute_first_guess.py).
    Returns None for the random solver — it always picks its own first guess.
    Raises ValueError if the entry is missing or empty for any other solver.
    """
    if solver_name == "random":
        return None

    if not _FIRST_GUESSES_PATH.exists():
        raise ValueError(
            f"first_guesses.json not found.\n"
            f"Run:  python compute_first_guess.py --size {size}"
        )

    with _FIRST_GUESSES_PATH.open() as f:
        data: dict = json.load(f)

    size_cfg = data.get(str(size))

    if size_cfg is None or solver_name not in size_cfg:
        raise ValueError(
            f"No first_guess entry for solver='{solver_name}', size={size} "
            f"in first_guesses.json.\n"
            f"Run:  python compute_first_guess.py --size {size}"
        )

    word = size_cfg[solver_name]
    if not word:
        raise ValueError(
            f"first_guess for solver='{solver_name}', size={size} is empty "
            f"in first_guesses.json.\n"
            f"Run:  python compute_first_guess.py --size {size}"
        )

    return word
